version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        USER_HOST: ${USER_HOST}
        UID_HOST: ${UID_HOST}
        GID_HOST: ${GID_HOST}
        APPNAME: ${APPNAME}
        SHARED_WORKSPACE_HOST: ${SHARED_WORKSPACE_HOST}
        SHARED_WORKSPACE_CONTAINER: ${SHARED_WORKSPACE_CONTAINER}
        NODE_VERSION: ${NODE_VERSION}
        # PORT_WEBPACK_BUNDLE_ANALYZER: ${PORT_WEBPACK_BUNDLE_ANALYZER}
    image: ${APPNAME}
    container_name: ${APPNAME}
    # ports:
    #   # webpack-bundle-analyzer用
    #   - ${PORT_WEBPACK_BUNDLE_ANALYZER}:${PORT_WEBPACK_BUNDLE_ANALYZER}
    volumes:
      - ./${SHARED_WORKSPACE_HOST}:${SHARED_WORKSPACE_CONTAINER}
      # ---------------------------------------------------------------------------
      # コンテナ側のnode_modulesディレクトリをホスト側に持ってこないようにする．
      # https://stackoverflow.com/a/37898591
      # なんかディレクトリ作られるけど，中身はホストへ共有されてない．まぁいいか…？
      # でもこれをすると，ホスト側の開発でエラーの赤波線が出てしまう…
      # - ${SHARED_WORKSPACE_CONTAINER}/frontend/node_modules/
      # - ${SHARED_WORKSPACE_CONTAINER}/backend/node_modules/
      # ---------------------------------------------------------------------------
      # 下記は緊急編集用．
      - ./docker/dev/tools:/opt/docker/tools
      # ---------------------------------------------------------------------------
    tty: true